### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by baumheld** [datalust/seq-input-gelf#125]
## After 2h (idle for the whole time) ~400MB
<img width="817" alt="image" src="https://github.com/datalust/seq-input-gelf/assets/141740877/0c3f6e5a-e3ff-4003-a721-a1f404913db1">

## After start ~40MB
<img width="1097" alt="image" src="https://github.com/datalust/seq-input-gelf/assets/141740877/d1456b75-b858-48b5-960b-74104b038641">

After some time the memory accumulates to 300-400 MB RAM. At the beginning `seq-input-gelf` sits around 40 MB RAM. My question is: Is 300-400 MB RAM considered normal? What would happen if I limit that containers memory to, let's say, 100MB?

This happens on our production server and also locally when testing with Docker Desktop.  
I'm using TCP with non-blocking mode, HTTPS and Traefik as reverse proxy.

Also, the CPU for seq-input-gelf is always between 2-4% when everything is idle. 

This is our stripped down `docker-compose.yml` file

```yaml
version: "3.9"

x-deploy: &hardware-limits
  resources:
    limits:
      memory: 2G

volumes:
  seq:

services:
  seq:
    container_name: seq
    image: datalust/seq:2023.4
    deploy: *hardware-limits
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: seqsvr/Client/seqcli node health -s http://127.0.0.1/
      timeout: 5s
      start_period: 30s
      interval: 5s
      retries: 10
    ports:
      - "5341:5341"
    environment:
      ACCEPT_EULA: Y
    volumes:
      - seq:/data

  seq-gelf-monitor:
    container_name: seq-gelf-monitor
    image: datalust/seq-input-gelf:3.0
    deploy: *hardware-limits
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      seq:
        condition: service_healthy
    stop_grace_period: 1s
    ports:
      - "127.0.0.1:12202:12201"
    environment:
      GELF_ADDRESS: tcp://0.0.0.0:12201
      SEQ_ADDRESS: http://seq:5341

```
